TASKS_SET = {
    "Turn on tv": [("tv", "is", "on")],
    "Turn on radio": [("radio", "is", "on")],
    "Turn on microwave": [("microwave", "is", "on")],
    "Turn on stove": [("stove", "is", "on")],
    "Turn on computer": [("computer", "is", "on")],
    "Turn on coffeemaker": [("coffeemaker", "is", "on")],
    "Turn on dishwasher": [("dishwasher", "is", "on")],
    "Turn on faucet": [("faucet", "is", "on")],
    "Turn on toaster": [("toaster", "is", "on")],
    "Open cabinet": [("cabinet", "is", "open")],
    "Open dishwasher": [("dishwasher", "is", "open")],
    "Open microwave": [("microwave", "is", "open")],
    "Open stove": [("stove", "is", "open")],
    "Open coffeepot": [("coffeepot", "is", "open")],
    "Open toilet": [("toilet", "is", "open")],
    "Open fridge": [("fridge", "is", "open")],
    "Put apple on desk": [("apple", "on", "desk")],
    "Put remotecontrol on desk": [("remotecontrol", "on", "desk")],
    "Put notes on desk": [("notes", "on", "desk")],
    "Put book on desk": [("book", "on", "desk")],
    "Put mug on desk": [("mug", "on", "desk")],
    "Put book on sofa": [("book", "on", "sofa")],
    "Put chips on sofa": [("chips", "on", "sofa")],
    "Put clock on sofa": [("clock", "on", "sofa")],
    "Put folder on sofa": [("folder", "on", "sofa")],
    "Put milk on sofa": [("milk", "on", "sofa")],
    "Put cereal on coffeetable": [("cereal", "on", "coffeetable")],
    "Put mug on coffeetable": [("mug", "on", "coffeetable")],
    "Put cutleryfork on coffeetable": [("cutleryfork", "on", "coffeetable")],
    "Put coffeepot on coffeetable": [("coffeepot", "on", "coffeetable")],
    "Put waterglass on coffeetable": [("waterglass", "on", "coffeetable")],
    "Put plate on microwave": [("plate", "on", "microwave")],
    "Put salmon on microwave": [("salmon", "on", "microwave")],
    "Put bananas on microwave": [("bananas", "on", "microwave")],
    "Put apple on microwave": [("apple", "on", "microwave")],
    "Put mug on microwave": [("mug", "on", "microwave")],
    "Put mug to tvstand": [("mug", "on", "tvstand")],
    "Put book on tvstand": [("book", "on", "tvstand")],
    "Put notes to tvstand": [("notes", "on", "tvstand")],
    "Put waterglass on tvstand": [("waterglass", "on", "tvstand")],
    "Put remotecontrol on tvstand": [("remotecontrol", "on", "tvstand")],
    "Put cellphone on bed": [("cellphone", "on", "bed")],
    "Put keyboard on bed": [("keyboard", "on", "bed")],
    "Put folder on bed": [("folder", "on", "bed")],
    "Put cereal on bed": [("cereal", "on", "bed")],
    "Put box on bed": [("box", "on", "bed")],
    "Place towel in closet": [("towel", "inside", "closet")],
    "Place keyboard in closet": [("keyboard", "inside", "closet")],
    "Place folder in closet": [("folder", "inside", "closet")],
    "Place mouse in closet": [("mouse", "inside", "closet")],
    "Place book in bookshelf": [("book", "inside", "bookshelf")],
    "Place folder in bookshelf": [("folder", "inside", "bookshelf")],
    "Place magazine in bookshelf": [("magazine", "inside", "bookshelf")],
    "Place paper in bookshelf": [("paper", "inside", "bookshelf")],
    "Place box in bookshelf": [("box", "inside", "bookshelf")],
    "Place plum in cabinet": [("plum", "inside", "cabinet")],
    "Place mug in cabinet": [("mug", "inside", "cabinet")],
    "Place cereal in cabinet": [("cereal", "inside", "cabinet")],
    "Place cupcake in cabinet": [("cupcake", "inside", "cabinet")],
    "Place paper in cabinet": [("paper", "inside", "cabinet")],
    "Place towel in cabinet": [("towel", "inside", "cabinet")],
    "Place box in cabinet": [("box", "inside", "cabinet")],
    "Place keyboard in cabinet": [("keyboard", "inside", "cabinet")],
    "Place box in closet": [("box", "inside", "closet")],
    "Place slippers in closet": [("slippers", "inside", "closet")],
    "Place cutleryknife in dishwasher": [
        ("cutleryknife", "inside", "dishwasher")
    ],
    "Place plate in dishwasher": [("plate", "inside", "dishwasher")],
    "Place mug in dishwasher": [("mug", "inside", "dishwasher")],
    "Place cutleryfork in dishwasher": [
        ("cutleryfork", "inside", "dishwasher")
    ],
    "Place milk in fridge": [("milk", "inside", "fridge")],
    "Place juice in fridge": [("juice", "inside", "fridge")],
    "Place apple in fridge": [("apple", "inside", "fridge")],
    "Place plum in fridge": [("plum", "inside", "fridge")],
    "Place carrot in fridge": [("carrot", "inside", "fridge")],
    "Place breadslice in microwave": [("breadslice", "inside", "microwave")],
    "Place cupcake in microwave": [("cupcake", "inside", "microwave")],
    "Place pancake in microwave": [("pancake", "inside", "microwave")],
    "Place pie in microwave": [("pie", "inside", "microwave")],
}
TASKS = list(TASKS_SET.keys())

SEEN_TASKS = [0, 4, 9, 14, 19, 24, 29, 34, 39, 44, 49, 54, 59, 64, 69, 74]
UNSEEN_TASKS = [x for x in range(len(TASKS)) if x not in (SEEN_TASKS)]
UNSEEN_TASKS_HALF = UNSEEN_TASKS[-24:]

SEEN_DOMAIN = [18, 20, 22, 24, 26, 28, 29, 31, 32, 34]
UNSEEN_DOMAIN = [0, 1, 5, 6, 7, 8, 9, 12, 13, 15]

ROOMS = ["kitchen", "bedroom", "livingroom", "bathroom"]
OBJECTS = [
    "alcohol",
    "amplifier",
    "apple",
    "bananas",
    "barsoap",
    "bathtub",
    "bellpepper",
    "bench",
    "boardgame",
    "book",
    "bottlewater",
    "breadslice",
    "cabinet",
    "carrot",
    "ceilingfan",
    "cellphone",
    "cereal",
    "chair",
    "chicken",
    "chips",
    "clock",
    "closet",
    "coffeetable",
    "computer",
    "cookingpot",
    "crayons",
    "cupcake",
    "curtains",
    "cutleryfork",
    "cutleryknife",
    "cutlets",
    "cuttingboard",
    "deodorant",
    "desk",
    "dishwasher",
    "faucet",
    "folder",
    "fridge",
    "fryingpan",
    "garbagecan",
    "hairproduct",
    "hanger",
    "juice",
    "keyboard",
    "knifeblock",
    "lightswitch",
    "lime",
    "magazine",
    "microwave",
    "milk",
    "milkshake",
    "mincedmeat",
    "mouse",
    "mousemat",
    "mug",
    "nightstand",
    "notes",
    "painkillers",
    "pancake",
    "paper",
    "papertray",
    "peach",
    "pear",
    "perfume",
    "photoframe",
    "pie",
    "plate",
    "plum",
    "poundcake",
    "printer",
    "pudding",
    "coffeemaker",
    "coffeepot",
    "radio",
    "remotecontrol",
    "salad",
    "salmon",
    "sink",
    "sofa",
    "speaker",
    "stove",
    "stovefan",
    "tablelamp",
    "toilet",
    "toaster",
    "toiletpaper",
    "toothbrush",
    "toothpaste",
    "towel",
    "toy",
    "tv",
    "tvstand",
    "washingmachine",
    "sponge",
    "waterglass",
    "whippedcream",
    "wine",
    "wineglass",
    "wallshelf",
]
